beta commit

diff --git a/rhinon/Dockerfile b/rhinon/Dockerfile
--- a/rhinon/Dockerfile
+++ b/rhinon/Dockerfile
@@ -7,7 +7,7 @@ WORKDIR /app
 COPY package.json package-lock.json* ./
 RUN \
   if [ -f package-lock.json ]; then npm ci; \
-  else echo "Lockfile not found." && exit 1; \
+  else echo "Lockfile not found ." && exit 1; \
   fi
 
 COPY . .
